Implement keepalive support
ContainerSSH/libcontainerssh pull request #15
Opened 2021-11-26 09:35 UTC by tsipinakis

## Please describe the change you are making

Teach containerssh about keepalive packets to avoid the logs being spammed by 'unknown global request logs'. Additionally, add settings for containerSSH to generate its own keepalives if necessary.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Sent with permission of the owner.

## The code will be published under the MIT-0 license. Have you read and understood this license?

Yes.

2021-12-03 09:35 UTC, janosdebugs requested changes
One minor change, otherwise looks good. Tests are needed though.

2021-12-03 09:35 UTC, janosdebugs commented on internal/sshserver/serverImpl.go
> +		if request.Type == "keepalive@openssh.com" {
Please implement it as a switch-case and put the components into separate functions. This function will need to be extended in the future. It's better to not create the need for refactoring later if we can avoid it.

2021-12-26 08:41 UTC, janosdebugs submitted a review, later dismissed
Looks good!

2022-01-04 10:15 UTC, tsipinakis commented
Squashed & signed, this needs a re-approval to be merged.

2022-01-04 10:30 UTC, janosdebugs approved these changes

2022-01-04 10:54 UTC, merged